### ISSUE TITLE
Devuelve { status: 'inlimit', status_text: 'Excedió el límite diario' }

### ISSUE THREAD

**Issue by lfalvarez** [mrpatiwi/rutificador#4]
Hola lo acabo de probar y se cae retornando un error "inlimit".

Tendrá que ver con los parámetros del header?

Chau

**Comment by jlobos** [comment]
Si tenia que ver con parámetros del header, se soluciono agregando `User-Agent` https://github.com/mrpatiwi/rutificador/commit/0be5adb18d3c9aeda2fe10711e243763d3548f5a

**Comment by lopezjurip** [comment]
@jlobos  Parece que te faltó actualizar el `package.json` al crear el tag. La mejor manera es haciendo `npm version [major|minor|patch]` para que lo suba solo y se cree el tag 😅

**Comment by jlobos** [comment]
@mrpatiwi jajaja si tienes razón :sweat_smile: ahora lo arregle :ok_hand:

**Comment by lopezjurip** [comment]
Publicado como `1.4.0`
