### ISSUE TITLE
Error: inlimit

### ISSUE THREAD

**Issue by seneiran** [mrpatiwi/rutificador#6]
Hey guys, 
i'm getting this issue :

Error: inlimit
    at request.then.then.then.then.json (/var/www/proyecto-test/node_modules/rutificador/index.js:38:15)

i was doing some testing and start failing. request limit exceeded maybe? 
do you have any idea or workaround to avoid it? 

Thanks in advance!

**Comment by gbelmm** [comment]
+1 help please

**Comment by seneiran** [comment]
The source page is dead, this proyect is dead too.

**Comment by jlobos** [comment]
@gbelmm @seneiran All problems fixed in last release 🎉
